import "./globals.css";
import { Inter } from "next/font/google";
import "./layout.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-white border-gray-200 dark:bg-gray-900">
          <div className="mx-auto flex max-w-screen-xl flex-wrap items-center justify-between p-4">
            <a href="https://flowbite.com/" className="flex items-center">
              <img
                src="https://img.icons8.com/?size=512&id=HwN2KHJZmGGN&format=png"
                className="mr-3 h-8"
                alt="Flowbite Logo"
              />
              <span className="dark:text-white self-center whitespace-nowrap text-2xl font-semibold text-pink-600">
                Art.io
              </span>
            </a>
            <button
              data-collapse-toggle="navbar-default"
              type="button"
              className="text-gray-500 hover:bg-gray-100 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 ml-3 inline-flex items-center rounded-lg p-2 text-sm focus:outline-none focus:ring-2 md:hidden"
              aria-controls="navbar-default"
              aria-expanded="false"
            >
              <span className="sr-only">Open main menu</span>
              <svg
                className="h-6 w-6"
                aria-hidden="true"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"></path>
              </svg>
            </button>
            <div
              className="hidden w-full md:block md:w-auto"
              id="navbar-default"
            >
              <ul className="border-gray-100 bg-gray-50 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700 mt-4 flex flex-col rounded-lg border p-4 font-medium md:mt-0 md:flex-row md:space-x-8 md:border-0 md:p-0">
                <li>
                  <a
                    href="./"
                    className="bg-blue-700 md:bg-transparent block rounded py-2 pl-3 pr-4 text-textColorMidnight md:p-0"
                    aria-current="page"
                  >
                    Home
                  </a>
                </li>
                <li>
                  <a
                    href="/about"
                    className="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-pink-500 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"
                  >
                    About
                  </a>
                </li>
                <li>
                  <a
                    href="/profile"
                    className="text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent block rounded py-2 pl-3 pr-4 md:border-0 md:p-0"
                  >
                    Profile
                  </a>
                </li>
                <li>
                  <a
                    href="/login"
                    className="text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:hover:text-pink-500 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent block rounded py-2 pl-3 pr-4 md:border-0 md:p-0"
                  >
                    Login
                  </a>
                </li>
                <li>
                  <a className="text-gray-900 hover:bg-gray-100 md:hover:bg-transparent md:hover:text-pink-500 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent block rounded py-2 pl-3 pr-4 md:border-0 md:p-0">
                    Sign Up
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="grid grid-cols-2 min-h-screen bg-white">
          <div className="bg-purple-100 rounded-lg p-14 m-14 h-[32rem]">
            <div>
              <h1 className="text-blue-900 antialiased font-bold text-3xl tracking-wider">
                Welcome to Art.io
              </h1>
              <p className="pt-5 font-light">
                Our platform is designed to empower artists like you to showcase
                and sell your unique digital creations as non-fungible tokens
                (NFTs).
                <br></br>
                <br></br>
                <div className="grid grid-cols-3 gap-6">
                  <div className="image-container">
                    <img
                      className="w-36 h-48"
                      src="https://gibbonsgazette.org/wp-content/uploads/2022/04/43YAWLITTZJLZIQTCP2JSS4KSM.jpg"
                      alt="NFT1"
                    />
                    <button className="p-2 mt-5 text-white rounded-lg bg-pink-500 text-center">
                      See more ⇒
                    </button>
                  </div>
                  <div className="image-container">
                    <img
                      className="w-36 h-48"
                      src="https://zarastro.art/wp-content/uploads/2021/07/Pop-Art-Ancient-Statue-1.jpeg"
                      alt="NFT1"
                    />
                    <button className="p-2 mt-5 text-white rounded-lg bg-rose-400 text-center">
                      See more ⇒
                    </button>
                  </div>
                  <div className="image-container">
                    <img
                      className="w-36 h-48"
                      src="https://nftcalendar.io/storage/uploads/events/2022/2/dpusazRUqM5jrjrQ0S3L2H19fbCQKxAMefj3INDr.gif"
                      alt="NFT1"
                    />
                    <button className="p-2 mt-5 text-white rounded-lg bg-orange-400 text-center">
                      See more ⇒
                    </button>
                  </div>
                </div>
              </p>
            </div>
            <ul className="m-5 underline-offset-auto text-center"> hello </ul>
          </div>
          <div className="bg-white">
            <div className="bg-pink-100 p-10 mt-7 h-48">
              <div>022</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
